spawnworld: world
spawnx: 0
spawny: 72
spawnz: 0
spawnyaw: -180
webpurify-api-key: asdf
aprilfoolsend: 1554177600
aprilfoolsmsg:
  - '&c===== WE''RE MOVING ====='
  - '&eWe''re making a new start on a new server!'
  - '&eMore info: x'
  - '&c===== WE''RE MOVING ====='